version: '3.6'
services:
  web:
    image: nginx:1.13.12-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mvc_docroot:/var/www/html/mvc_docroot
      - ./app:/var/www/html/app:ro

  app:
    build: ./mvc_docroot
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/app:ro
    links:
      - db

  db:
    image: mariadb:10.2
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - db-data:/var/lib/mysql
volumes:
  db-data:

