version: '3.6'
services:
  web:
    build: ./web
    container_name: web_c
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./web/nginx_default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./mvc_docroot:/var/www/html/mvc_docroot
      - ./app:/var/www/html/app:ro
      - log-data:/var/log/nginx

  app:
    build: ./mvc_docroot
    container_name: app_c
    user: www-data
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/app:ro
      - ./mvc_docroot:/var/www/html/mvc_docroot
    links:
      - db

  db:
    image: mariadb:10.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: db_c
    env_file:
      - .env
    expose:
      - "3306"
    volumes:
      - ./db/initial.sql:/docker-entrypoint-initdb.d/initial.sql:ro
      - db-data:/var/lib/mysql
volumes:
  db-data:
  log-data:

